"""T1 — core gate BEHAVIOR tests (regression-proofing manual checks).

The project's headline is a quality gate, so its behavior is tested directly:
does it FAIL on a real regression, PASS on an identical re-run, and resist false
alarms on noise-band-sized changes? These pin numbers we previously verified by
hand. The gate is deterministic (noise std=0), so expected verdicts are exact.

Inputs reuse existing examples/ fixtures; the 1-case fixture is generated by
tests/fixtures/make_fixtures.py (see tests/fixtures/README.md).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest

from app.core.service import build_gate_result

BASELINE = "examples/allganize_baseline"
CANDIDATE = "examples/allganize_candidate"          # top_k 5→1 (real regression)
ONE_CASE = "tests/fixtures/allganize_candidate_1case"  # 1-case flip (noise-sized)


def _metrics(rows) -> set[str]:
    return {r.metric for r in rows}


def test_gate_fail_on_topk_regression():
    """top_k 5→1 → FAIL (exit 1); answerable_accuracy + retrieval_miss flagged."""
    g = build_gate_result(BASELINE, CANDIDATE)
    assert g.verdict == "FAIL"
    assert g.exit_code == 1
    regressed = _metrics(g.regressions)
    assert "answerable_accuracy" in regressed   # 0.55 → 0.30
    assert "retrieval_miss" in regressed        # 1 → 5
    assert all(r.significant and r.direction == "regression" for r in g.regressions)


def test_gate_pass_on_identical_run():
    """Same run as baseline AND candidate → PASS (exit 0), no regressions.
    Pins 'same config re-run is always PASS' (zero false alarms)."""
    g = build_gate_result(BASELINE, BASELINE)
    assert g.verdict == "PASS"
    assert g.exit_code == 0
    assert g.regressions == []


def test_noise_band_floor_prevents_false_alarm():
    """A 1-case change (≈ noise band, at the ±1-case floor) must NOT FAIL."""
    g = build_gate_result(BASELINE, ONE_CASE)
    assert g.verdict != "FAIL"
    assert g.exit_code == 0
    assert g.regressions == []   # nothing crosses the significance+floor bar


def test_warn_on_borderline_change():
    """Same 1-case fixture: one borderline signal → WARN (neither FAIL nor PASS).
    A single-case answerable_accuracy dip is significant-ish but inside the band/floor,
    so it surfaces as a warning, not a FAIL."""
    g = build_gate_result(BASELINE, ONE_CASE)
    assert g.verdict == "WARN"
    assert g.exit_code == 0
    assert len(g.warnings) >= 1
